### ISSUE TITLE
Support scheduling at AWS Organizations level

### ISSUE THREAD

**Issue by rdkls** [aws-solutions/aws-instance-scheduler#141]
The main use-case is not having to maintain the list of ARNs or Account IDs within my org, and have this dynamically retrieved on each run from organization.list_accounts()

It would be possible to have a config parameter for an IAM Role Name (e.g. "OrgInstanceScheduler") and assuming this set up in all tenant accounts, use the api organization.list_accounts() construct the ARN, assume them, and schedule accordingly.
Ideally do this multi-threaded in all accounts simultaneously.

**Comment by whoDoneItAgain** [comment]
can this be reopened since v2 was pulled? It would be a highly useful feature.

**Comment by nalalia-1702** [comment]
@rakshb @gockle is this feature working now? 
very useful feature...
