### ISSUE TITLE
exceeded quota of values in SSM Parameter

### ISSUE THREAD

**Issue by ziyadmhd** [aws-solutions/aws-instance-scheduler#155]
I have been using ssm parameter to pass the IAM role arns for the lambda to assume. I have been using an Advanced parameter but since we have large number of accounts, it simply exceeded the limit. how do i do this for newer accounts now ?

**Comment by ziyadmhd** [comment]
Can you please provide an update on this

**Comment by jgardsentry** [comment]
With Advanced parameters you have a limit of 100,000 per account ([ref](https://docs.aws.amazon.com/general/latest/gr/ssm.html#limits_ssm)).  You're exceeding that?

**Comment by deolank** [comment]
Can you provide more information around how many accounts/roles you are trying to use?

**Comment by kruule69** [comment]
We just ran into this issue, it's related to the size of the SSM Paramater allowed.  Standard SSM Param value size allowed is 4k, Advanced is 8k.  When trying to add more CrossAccountRoles to it, we can't add more due to the limitation of the Param Value Size.  We only have about 80 Accounts.
Is this still an issue or is there a workaround?

**Comment by ozeebee** [comment]
As explained [here](https://github.com/awslabs/aws-instance-scheduler/issues/120), you can specify a list of parameters which means you have to split your list of accounts into multiple parameters...
I know, this is a hassle but this is the only work-around I'm aware of.
But if you find another solution, please let us know ;)

**Comment by kruule69** [comment]
Thanks for this, it may help.  I re-read a few times the documentation (https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/instance-scheduler.pdf) and it really isn't that clear that this is an option and only says a comman separated list, not the syntax.  I'm assuming the syntax is something like: '{param:/instanceScheduler/CrossAccountRoles,/instanceScheduler/CrossAccountRoles2}'

**Comment by ozeebee** [comment]
@kruule69  Actually, I think you have to specify multiple parameters like this if I remember well: `{param:/scheduler/accounts1},{param:/scheduler/accounts2}`
And then you create corresponding SSM parameters with comma-separated list of cross-account role ARNs.

**Comment by phlrnnr** [comment]
> Thanks for this, it may help. I re-read a few times the documentation (https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/instance-scheduler.pdf) and it really isn't that clear that this is an option and only says a comman separated list, not the syntax. I'm assuming the syntax is something like: '{param:/instanceScheduler/CrossAccountRoles,/instanceScheduler/CrossAccountRoles2}'

I agree, the documentation is not clear at all that this is an option.  I was trying to understand what was meant by "You can store cross-account ARNs as a list parameter where every item is an ARN"  -- there is no parameter type = list.  So, I'm guessing this is what is being referred to.

@ozeebee thanks for your help in finding a workaround for this.
