### ISSUE TITLE
CloudFormation template error (Mapping --> Timeouts)

### ISSUE THREAD

**Issue by eduardopuente** [aws-solutions/aws-instance-scheduler#205]
Parameter ScheduleExpression is not valid. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException

This is because on the defined mappings, there is an error:
`"60": "cron(0/1 * * ? *)"` should be `"60": "cron(0/60 * * ? *)"`

**Comment by gockle** [comment]
@eduardopuente Thanks for providing this information, we will patch is error in a future release.

**Comment by paultung** [comment]
The actually error is here:
[source/lib/aws-instance-scheduler-stack.ts#L615](https://github.com/awslabs/aws-instance-scheduler/blob/107aa722d01c32713ed31a6acbb73b0395527387/source/lib/aws-instance-scheduler-stack.ts#L615)

I think it should be:
`cron(0/60 * * * ? *)` or `cron(0 0/1 * * * ? *)`

FYR~

**Comment by gockle** [comment]
@eduardopuente Issue has been resolved in the latest version of the solution v1.4.0.
