### ISSUE TITLE
Unable to deploy Instance Scheduler template as a Nested Stack (within a StackSet)

### ISSUE THREAD

**Issue by micklaing** [aws-solutions/aws-instance-scheduler#214]
The instance-scheduler.template generates the "Main" resource Lambda Function name using the following code

        "FunctionName": {
          "Fn::Join": [
            "",
            [
              {
                "Ref": "AWS::StackName"
              },
              "-InstanceSchedulerMain"
            ]
          ]
        },

If the template is deployed as a Nested Stack, the AWS::StackName is generated by CloudFormation. This causes the above concatenation to exceed the 64 character limit for a Lambda Function name (the AWS::StackName is 100 characters long before adding the hard coded suffix). 

This could be easily overcome by allowing the FunctionName to be passed in as a parameter to the template (optionally with a default value pre-populated), rather than forcing an unconstrained string concatentation.

**Comment by gockle** [comment]
Hi @micklaing-kcom sorry about the issue. We will review it and address the issue in a future release.

**Comment by rakshb** [comment]
We reviewed this request in detail and we do not support the usage of Instance Scheduler as a nested stack. The workaround that we would recommend is to directly customize the instance scheduler template to remove the lambdafunction name.
