### ISSUE TITLE
Feature Request: Parameter to enable Point In Time for DynamoDB for Security Hub

### ISSUE THREAD

**Issue by Papina** [aws-solutions/aws-instance-scheduler#235]
using the default json implementation 
at https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/instance-scheduler.template 
from https://aws.amazon.com/solutions/implementations/instance-scheduler/

Security Hub fails on:
AWS Foundational Security Best Practices v1.0.0
ID                    | Title
--------------|---------------
DynamoDB.2 | DynamoDB tables should have point-in-time recovery enabled

for the two tables created

suggestion is to add pointintimerecoveryspecification to the json, or a parameter that can turn it off or on

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-pointintimerecoveryspecification.html

**Comment by gockle** [comment]
@Papina Thanks for the feedback, we will include this in our next scheduled release.
