### ISSUE TITLE
Feature request: Custom role path for lambda role

### ISSUE THREAD

**Issue by wmic-wzacharias** [aws-solutions/aws-instance-scheduler#264]
Hello, I have a use case where I'm deploying the lambda into an account that requires the execution role to be at a specific path to work with the security controls. Currently there is no way to specify a custom path at cdk build time, and it's not available as a parameter of the template. 
Is this a feature that could get added? I'd be happy to submit a PR to add the feature if so.

**Comment by gockle** [comment]
@wmic-wzacharias You can download the [solution template](https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/aws-instance-scheduler.template), 

Modify the Resources SchedulerRole, by adding the custom rolename,
```
"RoleName": [PROVIDE_ROLE_NAME]
``

* In case you need to update the remote template you can do a similar change to add a role name, and make the same changes in the solution template to the sts:AssumeRole policy. 
* In case that you want to provide a custom role outside of the solution, you can modify the template accordingly and provide the reference name in the template.

Let me know if this helps, for now, as for the feature to be able to provide a custom name, we cannot add that as part of the solution currently as there are other changes being planned for the solution.
