### ISSUE TITLE
Manually stoped instance not starting back up at next period

### ISSUE THREAD

**Issue by JB4dev** [aws-solutions/aws-instance-scheduler#268]
Hello everybody,

my setup is the following:

one EC2 Instance, tagged correctly
Im using a schedule frequency of 15 minutes.

The schedule I’m using is:
```
{
  "type": {
    "S": "schedule"
  },
  "name": {
    "S": "scale-ec2-streaming"
  },
  "timezone": {
    "S": "Europe/Berlin"
  },
  "description": {
    "S": "scaling of ec2 instances for streaming"
  },
  "periods": {
    "SS": [
      "after-streaming-hours@t2.micro",
      "befor-streaming-hours@t2.micro",
      "not-streaming-days@t2.micro",
      "streaming-hours@g4ad.xlarge"
    ]
  }
}
```

The periods I’m using:

```
{
  "type": {
    "S": "period"
  },
  "name": {
    "S": "befor-streaming-hours"
  },
  "begintime": {
    "S": "00:00"
  },
  "endtime": {
    "S": "17:14"
  },
  "description": {
    "S": "streaming day and time"
  },
  "weekdays": {
    "SS": [
      "thu"
    ]
  }
}
```

```
{
  "type": {
    "S": "period"
  },
  "name": {
    "S": "streaming-hours"
  },
  "begintime": {
    "S": "17:30"
  },
  "endtime": {
    "S": "20:14"
  },
  "description": {
    "S": "Streaming hours on thursdays"
  },
  "weekdays": {
    "SS": [
      "thu"
    ]
  }
}
```

```
{
  "type": {
    "S": "period"
  },
  "name": {
    "S": "after-streaming-hours"
  },
  "begintime": {
    "S": "20:15"
  },
  "endtime": {
    "S": "23:59"
  },
  "description": {
    "S": "streaming day and time"
  },
  "weekdays": {
    "SS": [
      "thu"
    ]
  }
}
```

```
{
  "type": {
    "S": "period"
  },
  "name": {
    "S": "not-streaming-days"
  },
  "description": {
    "S": "not streaming days"
  },
  "weekdays": {
    "SS": [
      "fri-wed"
    ]
  }
}

```

**Usecase:** 
During the week the instance shall run on t2.micro and during the „streaming-hours“ period it shall scale to a g4ad.xlarge instance type. If my performance use case is done earlier than specified in the „streaming-hours“ period I manually shut down the instance.

**Problem:** 
The instance is not coming back up and is not being scaled at the subsequent period, which is "after-streaming-hours"

According to the documentation https://docs.aws.amazon.com/solutions/latest/instance-scheduler/components.html the instance should come back up at the "after-streaming-hours" period. Am I missing something here?

**CloudWatch Log:**
```
DEBUG   : Desired state for instance from schedule "scale-ec2-streaming" is running, last desired state was running, actual state is stopped, desired type is t2.micro 
INFO    : Scheduler result {‚xxxxx‘: {'started': {}, 'stopped': {}, 'resized': {}}}
```

Thanks for your comments

**Comment by gockle** [comment]
@JB4dev Can you try enabling the attribute "enforced"=True in the schedule, to see if that resolves this issue?

**Comment by JB4dev** [comment]
Hey @gockle 
thanks for your suggestion.

with regard to the enforce attribute the documentation says:

> Schedules contain an enforced field that allows you to prevent an instance from being manually started outside of a running period, or manually stopped during a running period. If this field is set to true and a user manually starts an instance outside of a running period, the solution will stop the instance. If this field is set to true, it also restarts an instance if it was manually stopped during a running period. 

So from my understanding that would mean that i can no longer shut down my performance usecase earlier than specified. This would not be a good solution.

As a workaround i could create two schedules in two different CloudFormation stacks i guess. One containing the t2.micro usecases and being enforced and one containing the performance usecase being not enforced. But this seems like an dirty workaround.

Is there somebody who can tell me if the behavior described above is a bug or a feature?

Thanks!

**Comment by gockle** [comment]
@JB4dev I took some time to replicate this issue and here is what I have done,

**Comment by gockle** [comment]
@JB4dev I tried replicating the scenarios and  following are the steps I had performed,

1. I created the three time periods for a single day, 00:00 to 17:14 (before-streaming-hours), 17:30 to 20:14 (streaming-hours), 20:15 to 23:59 (after-streaming-hours),
2. Instead of waiting for current time to fall within these time ranges to check if the solution is working or not I had to keep adjusting the periods to create the scenarios,
3. I tried to make sure that the instance is within the time frame of streaming-hours period and manually i stopped the instance, then I adjusted the periods to see that the instance waits until the current time is within the time range of after-streaming-hours, 
4. After I had manually stopped the instance the solution brought the instance back up in t2.micro when the current time was within the range of the after-streaming-hours.


So the solutions seemed to work for me as expected, Before I go any further can you confirm if the solutions is using the latest version v1.4.0? we had an earlier issue in the previous versions where the code would not evaluate the timezones correctly when using the weekday for single days i.e. tue/thu and as the timezone here is listed as Europe/Berlin, I want to rule out if that is the issue.

If you are already running the latest v1.4.0 version, can you confirm if there is any changes I need to make in the way I evaluated the scenario?

**Comment by JB4dev** [comment]
Hey @gockle 

Thanks for your effort.

Yes my stack is running on version v. 1.4.0
> SO0030) - The AWS CloudFormation template for deployment of the aws-instance-scheduler, version: v1.4.0

To be honest, your scenario seems to be fine and comparable to mine. Very weird that it is working for you but not for me.
I tried to deploy a new stack with the same period/schedule config to rule out any config errors. Still the same issue.

But I found something else that is interesting. In the DynamoDB, the StateTable is not updated correctly. Even though the EC2 instance has been stopped manually, the state inside the StateTable is „running“. If I remove the state column. The Instance gets scaled and started up correctly. 

So it seems that even though the CloudWatch log indicates that the EC2 status is retrieved correctly it is not stored correctly inside the StateTable which causes the Scheduler to not work properly. In case the EC2 instance gets stopped by the scheduler the state inside the StateTable is updated corretly.

What do you think? Is this thesis valid?

Thanks!

**Comment by gockle** [comment]
@JB4dev Your observation is correct, when the instance is manually stopped or started, the State Table doesn't show the new state as this table is being updated by the solution when it enforces the scheduling logic. If the state table entry for the instance is either removed the solution will attempt to restart the instance. I will investigate this further and get back to you.

**Comment by JB4dev** [comment]
Hey @gockle,
any updates regarding this topic?

**Comment by gockle** [comment]
@JB4dev I couldn't replicate the issue, the instance was being started when the scheduler was able to find a valid period range after being stopped manually. All the tests I had performed I had done it 5 minute interval. The only difference I found between the scenarios that you have been running and mine is that, between the periods before-streaming-hours and streaming-hours you are maintaining a 16 minute window when the instance should be stopped, but if the solution doesn't evaluate exactly within that time frame even once, the state table will not have the correct status, and hence the solution might not start the instance, Can you try switching to a 5 minute frequency for the scheduler and check if this scenario works?
