### ISSUE TITLE
Deployed v2.0.0 of aws-instance-scheduler but after configuring schedule and period to start/stop tagged instance, it did not start/stop any ec2 instance 

### ISSUE THREAD

**Issue by rohan-1995** [aws-solutions/aws-instance-scheduler#276]
After deploying v2.0.0, having parameter tag 'Schedule', I configured values for my testing schedule "test-office-hours" and its period. I tagged ec2 instance in stopped state with my tag 'Schedule: test-office-hours" but it does not start my instance. In streamed debug logs, i do not see any information or even mention of my ec2 instance and  lambda function shows successful invocations. I have tried changing 'SchedulerFrequency' parameter to 1 minutes as well. it does not seem to fix. Can you please take a look into this issue if there is any issue of lambda ?

**Comment by gockle** [comment]
hi @rohan-1995 

Just to confirm the tags are case sensitive, so tag key should be `Schedule` and tag value should be `test-office-hours`. You can check if the ec2 instance is being picked by the SSM Automation using the `ssm-execution-id` stored for each schedule in the `*-ScheduleStatesTable-*` table. You can retrieve the information for the AWS Systems Manager > Automations console and searching for the ssm-execution-id.

If the you want enforce the same schedule multiple times, you can delete the schedule entry in the `*-ScheduleStatesTable-*` when the Lambda runs for the next timed invocation it will retry the schedule i.e it will start the automation document again.

**Comment by TimTraylor** [comment]
> ok, i have the same issue. After digging into it, found that the SSM Automation execution (for me it was Scheduler-StopTaggedEC2Instances-v2.0.0) failed because: `The provided role: arn:aws:iam::XXXXXXXXXXXX:role/Dev-Scheduler-AutomationExecutionRole-us-east-1 can't be assumed. (Service: null; Status Code: 0; Error Code: null; Request ID: null; Proxy: null) `
> 
> I looked up the mentioned role - it wasn't indeed created.
> 
> *obviously, i obfuscated my account id (XXXXXXX is not the actual output)

I can confirm the same behavior vaspoz is having.

**Comment by ionutz89** [comment]
Thank you for your reply. I doubled checked them and all seem ok. 

Just to make sure before contacting you, I tried to rebuild couple of times(deploy/delete stacks).

**Comment by gockle** [comment]
@ionutz89 If both the templates are deployed successfully and all the roles, policies have been created and if you continue to see the error `The provided role: arn:aws:iam::XXXXXXXXX:role/Dev-Scheduler-AutomationExecutionRole-eu-west-1 can't be assumed. (Service: null; Status Code: 0; Error Code: null; Request ID: null; Proxy: null)`, create a AWS Support ticket and provide the scenario, as the solution relies on Systems Manager to perform the scheduling.
