### ISSUE TITLE
Instances not stopping or not stopping as expected

### ISSUE THREAD

**Issue by AleiScho** [aws-solutions/aws-instance-scheduler#279]
I tried to create a Schedule which shuts down every tagged instance at 6PM (combined with a lambda which automatically tags every newly created instance, unless already tagged). My goal is that if there is a newly created instance for testing, and the instance is forgotten, it does not run for several days incuring costs. It also should not restart the next day.

Schedule I created:
      type: "schedule"
      name: "shutdown"
      description: "shutdown-schedule"
      periods: "shutdown-period"
      timezone: "Europe/Berlin"
Period I created:
      type: "period"
      name: "shutdown-period"
      description: "shutdown period"
      endtime: "18:00"

The behaviour was not as expected.
If I first create my instance and tag it, and then create the schedule, my instance shuts down at the next 5 minute tick, no matter if it is before or after 6PM.

If I create the schedule first, wait for the next 5 minute tick, and then create my instance and tag it, it never shuts down. Doesn't matter if I do it before 6PM, after 6PM, wait for 6PM to pass, change the endtime to a time before the current time, change it to a time after the current time, ....

What I noticed is that it depends on the existence of an entry in the "ScheduleStatesTable" in DynamoDB. If I have the second case (first schedule, then instance) where my instance never shuts down, if I delete the entry "shutdown" from the table then the instance will shut down at the next 5 minute tick.

It seems that once the state of the entry has changed to "stopped", it does not evaluate any running instances that were created after the state change (or tagged after the state change). Combined with the fact that I do not have a begintime (I do not want my instance to start automatically with this tag), the entry "shutdown" in the "ScheduleStatesTable" becomes "stopped" immediately after creation and never changes. So now I have a schedule which does not stop at the intended time, and only does so once.

**Describe the bug**
Schedule with only endtime does not work if instance is tagged after creation of schedule, and immediately shuts down instance if tagged before creation of schedule.

**To Reproduce**
- Create 2 Instances
- Tag one instance
- create schedule
- wait for the next 5 minute tick, then tag second instance
- One instance shuts down at the next tick even if it is not yet supposed to
- The other will never shut down, even after endtime
- Delete the entry from the "ScheduleStatesTable" and the instance will stop at the next tick

**Expected behavior**
- Instances keep running and then shut down at 6 PM
- If instances are started or newly created the next day, the will shut down at 6PM of the next day

**Please complete the following information about the solution:**
- Version: v2.0.0

- Region: eu-central-1
- Was the solution modified from the version published on this repository? No changes were made

**Comment by 65156** [comment]
@gockle You are not able to target specific EC2 instances by tag using AWS Systems Manager, the EC2s need to be explicity specified, this is not an answer.

from the documentation instance scheduler should be able to simply stop an instance on a schedule.
