### ISSUE TITLE
Assign schedule for ec2 OR rds, not both

### ISSUE THREAD

**Issue by ashraf133** [aws-solutions/aws-instance-scheduler#285]
**Is your feature request related to a problem? Please describe.**
I want to assign a schedule only to ec2 ( in the table config i habe both ec2 and rds)
**Describe the feature you'd like**
i want to force scheduled_services in schedule

**Comment by gockle** [comment]
Hi @ashraf133 Thanks for the feedback, you can install the solution in different account/regions with EC2 and RDS individually and use the solution, we will not be supporting this use case as it can be currently accomplished by installing multiple stacks in different accounts.
