### ISSUE TITLE
stopped instances are not correctely tagged 

### ISSUE THREAD

**Issue by ashraf133** [aws-solutions/aws-instance-scheduler#286]
**Describe the bug**
Aws sheduler is not correctly tagging stopped instance

**To Reproduce**
Stop instance using Aws Scheduler 2.0

**Expected behavior**
tag on stopped instance should be : 
"StateChanged": "Resource stopped by Instance Scheduler"

**Actual behavior**
Stopped instances are tagged :
"StateChanged": "Resource started by Instance Scheduler"

**Please complete the following information about the solution:**
- [x] Version:  v2.0.0

**Comment by gockle** [comment]
Hi @ashraf133 Thanks for the feedback we will look into this and update the solution in the next release if required.
