### ISSUE TITLE
Which version will be maintained ?

### ISSUE THREAD

**Issue by ashraf133** [aws-solutions/aws-instance-scheduler#289]
Hello,

You will continue to maintain the two versions ( 1.4 and 2.0 ) or only 2.0 ?
am planning to implement aws scheduler and i want to be sure about that.

Thank you

**Comment by gockle** [comment]
Hi @ashraf133 The version v2.0.0 has been rolled back, v1.4.0 will be the latest until a new version is released.

**Comment by creeder-uturn** [comment]
@gockle Is there any information on why it was rolled back and whether it will be redeployed, or whether a variant on 1.4 is more likely? I couldn't find that information anywhere obvious.

For someone currently using 2.0.0, should they rebuild using 1.4.0 given the opportunity to ensure ongoing maintenance, or just wait for the next version and coast on their current setup?

**Comment by gockle** [comment]
Hi @creeder-uturn You can rollback the stack deployed using (v2.0.0 template) using the CloudFormation template for v1.4.0 available [here](https://aws.amazon.com/solutions/implementations/instance-scheduler/?did=sl_card&trk=sl_card)

**Comment by fergoid2511** [comment]
Is it possible to have some information on why 2.0.0 was pulled?

**Comment by gockle** [comment]
*Which version will be maintained?* 
The AWS Solution team has made an update to AWS Instance Scheduler: we’ve rolled back to Version 1.4.0 from Version 2.0.0. We will maintain Version 1.4.0 until further notice.

*What is the reason for the roll back?*
When customers grow in their number of accounts and schedule count, they may experience a spike in cost when using Version 2.0.0. By rolling back to Version 1.4.0, the solution will revert to using lambda functions and keep customer costs as they were previously experienced. Ultimately, this roll back will ensure customers don’t see any spike in the solution costs.

 *What documentation has changed?*

1. The Solution Overview (https://aws.amazon.com/solutions/implementations/instance-scheduler/) has been updated
2. TheImplementation Guide (https://docs.aws.amazon.com/solutions/latest/instance-scheduler/welcome.html)has been updated
