### ISSUE TITLE
unable to create schedule referencesing ssm maint window.

### ISSUE THREAD

**Issue by Chris-Pr** [aws-solutions/aws-instance-scheduler#290]
Hi, I have multple periods and schedules working, but I am unable to create a schedule that uses a SSM MAINT window using the scheduler-cli

Can someone please give a cli example for stepped process for creating a schdedule with a SSM maint window please and pre reqs. It is not clearly explained in the support document nor is there a cli example.

Much appreciated.

**Comment by gockle** [comment]
Hi Chris-Pr,

Enable the cloudformation parameter __Enable SSM maintenance windows__ and update the stack, once the update is successfully, update the schedule using the scheduler cli with the maintenance window name. Documentation for update_schedule command is [here](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/scheduler-cli.html#update-schedule)

```
# SAMPLE COMMAND review the current attributes in the schedule and provide them here, as they will be lost once the update is complete
scheduler_cli update_schedule --stack [STACK_NAME] --name [SCHEDULE_NAME] --periods [periodname] --use-maintenance-window --ssm-maintenance-window [MAINTENANC_WINDOW_NAME]
```

**Comment by Chris-Pr** [comment]
Thank you @gockle , I see you a required to add a --period, but what if you only want to use maint window import as period, with no additional --period?

use case for this is to turn on offline instances for monthly patching which is controlled by system manager maintenance windows.

**Comment by gockle** [comment]
@Chris-Pr The solution is not designed to handle the scenario where only the maintenance window is provided in a schedule, SSM maintenance window can be created with feature to run multiple automations, you can review the maintenance window and use the `Register Tasks` option to start and stop ec2 instances using SSM Documents. 

* AWS-StartEC2Instance
* AWS-StopEC2Instance
