### ISSUE TITLE
AccountId is missing in publish message to SNS topic  from Instance Scheduler Lambda

### ISSUE THREAD

**Issue by anuj1366** [aws-solutions/aws-instance-scheduler#292]
Hi Team,
Currently I am using Instance scheduler for more than 100+ account and currently I am facing one issue to figure out the error message publish to SNS topic through Instance scheduler main Lambda, is from which Account ID. 
Is there any way to figure out the error publish to SNS topic belongs to which account Id. Is there any field we can use to get he accountID from publish message?

**Comment by gockle** [comment]
Hi @anuj1366 The message includes the logstream name, which will have further details for the account and the error type. Are you able to view the logstream name in the message?

* Refer to method `publish_to_sns` in [Logger.py](https://github.com/aws-solutions/aws-instance-scheduler/blob/master/source/lambda/util/logger.py)

```

message = "Loggroup: {}\nLogstream {}\n{} : {}".format(self._loggroup, self._logstream, level, msg)

```
