### ISSUE TITLE
schedule does not work as expected

### ISSUE THREAD

**Issue by dwang13** [aws-solutions/aws-instance-scheduler#294]
Hi
We are trying to create a new schedule to do the following:
start the instance at 10pm on Sunday and stop it at 7pm on Friday.
Here is the yaml file:
AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer': {}
Resources:
  PutnameScheduler:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      Name: EST-Sun-2200-START-Fri-1900-STOP
      NoStackPrefix: 'True'
      Description: Putnam Instance Schedule
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:infra-instancescheduler-InstanceSchedulerMain
      Enforced: 'False'
      Metrics: 'True'
      Timezone: America/New_York
      Periods:
        - Description: start at 10pm on Sunday
          BeginTime: '22:00'
          WeekDays: Sun
        - Description: stop at 7pm on Friday
          EndTime: '19:00'
          WeekDays: Fri

However, it does not work as we expect.  When we assign the schedule to an instance, it stops the instance at the next run of the lambda even though it is not 10pm on Sunday.

Could anyone please let me know if it is misconfigured?
Thanks!
Dian

**Comment by gockle** [comment]
@dwang13 The period should have the begintime and endtime if multiple periods are configured in a schedule, refer the documentation section [Start and stop times](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/components.html)

you can try the following configuration for your requirement,
period1: begintime 22:00 endtime 23:59 weekdays sun
period2: begintime 00:00 endtime 23:59 weekdays mon-thu
period3: begintime 00:00 endtime 19:00 weekdays fri

**Comment by dwang13** [comment]
Gockle
Thank you so much for the quick response.
ok, I will try the suggestion.
Dian
