### ISSUE TITLE
How to avoid Instance Scheduler to pick RDS Aurora Serverless?

### ISSUE THREAD

**Issue by anuj1366** [aws-solutions/aws-instance-scheduler#297]
Currently We have a scenario where we want to avoid Instance Scheduler to pick RDS Aurora Serverless for scheduling and we can not remove tag as well from RDS Aurora Serverless.

Currently Intance scheduler is trying to schedule "RDS Aurora Serverless" but getting error and same error we are getting on SNS topic.

So is there any way, we can avoid Instance Scheduler to pick RDS Aurora Serverless?

**Comment by gockle** [comment]
Hi @anuj1366 the instances should be untagged, but if the tagging is required, the following conditional check can be added in the method `get_schedulable_rds_clusters` in the file  `schedulers/rds_service.py`. 

```
            if cluster_inst["EngineMode"] in ["serverless"]:
                return False
```

Entire function reference:
```
def get_schedulable_rds_clusters(self, kwargs):
        def is_schedulable(cluster_inst):

            db_id = cluster_inst["DBClusterIdentifier"]

            state = cluster_inst["Status"]

            if cluster_inst["EngineMode"] in ["serverless"]:
                return False

            if state not in RdsService.RDS_SCHEDULABLE_STATES:
                self._logger.debug(DEBUG_SKIPPING_INSTANCE, "cluster", db_id, state)
                return False

            if self.rds_resource_tags.get(cluster_inst["DBClusterArn"]) is None:
                self._logger.debug(DEBUG_NO_SCHEDULE_TAG, cluster_inst, self._tagname)
                return False

            return True

        return self.get_schedulable_resources(fn_is_schedulable=is_schedulable,
                                              fn_describe_name="describe_db_clusters",
                                              kwargs=kwargs)

```

**Comment by anuj1366** [comment]
thank you @gockle for your comments. I will test the scenario based on the changes suggested by you :)
