### ISSUE TITLE
Our Instance schuler Lamnda is getting timeout

### ISSUE THREAD

**Issue by anuj1366** [aws-solutions/aws-instance-scheduler#298]
Hi Team,
We are using Instance scheduler 1.3 version and currently we are trying to schedule 500+ accounts.
We have given Instance scheduler lambda timeout 15 min, but still all the ec2/rds instances are not able to start/stop at configured time because of timeout.

Please suggest any suggestion how to schedule 500+ accounts with configured time without any delay.

**Comment by gockle** [comment]
Hi @anuj1366
* First can you update the stack to the latest version of v1.4.0, it has some fixes not related to the API/Performance but that is recommended.
* Can you provide the following details how many regions, how many services are being configured (ec2, rds or both)
* Do you use ssm maintenance windows configured in the schedules?

The solution goes through all the configurations and creates multiple lambda executions sequentially but milliseconds apart, so if you have 500 accounts, 2 regions, 2 services, frequency 5 minutes

Number of Lambda executions every 5 minutes = 500 * 2 * 2 = 2000

* How many lambda functions are timing out? are all of them timing out or only some of the lambda executions are timing out?



Is the account where the solution is deployed in reaching the limits of the lambda executions (check the service limit of number of concurrent lambda executions allowed in the account)? As its a possibility that there are other services which are also using Lambda and you might be reaching a limit?

**Comment by anuj1366** [comment]
Hi @gockle 

- Currently we are using Instance Scheduler v1.3.3
- Currently we have configured 3 region and configured both ec2 and rds both services.
- service limit of number of concurrent lambda executions allowed in the account = 3000
- Number of Lambda executions every 5 minutes = 582 * 3 * 2 = 3492
- Lambda timout is set 15 min and lambda memory set = 200MB
- Please find the below screen shot for reference. Below screen shot are from Instance scheduler lambda.
![image](https://user-images.githubusercontent.com/91662053/149490165-fa41ac70-e5d7-402c-9f5a-eaad2d68e16e.png)
![image](https://user-images.githubusercontent.com/91662053/149490252-34da5800-ea2f-4c23-b045-d0001b64f4c7.png)
![image](https://user-images.githubusercontent.com/91662053/149490299-ed030ae6-f483-453f-8f4e-356b4db1c826.png)
![image](https://user-images.githubusercontent.com/91662053/149490412-ff21c9ba-d8aa-45d3-850e-5dc44594b3d8.png)

**Comment by gockle** [comment]
Hi @anuj1366 Can you try updating increasing the frequency of the Lambda every 30 minutes, The concurrency limit might be playing a role in increased timeouts or delays schedule evaluation which can result in the same the instances not being started or stopped? Also update the stack to the latest version v1.4.0.
