### ISSUE TITLE
Rolling Back 

### ISSUE THREAD

**Issue by bbenson29** [aws-solutions/aws-instance-scheduler#299]
How can I roll back from v2 back to v1.4? 
My installation was done initially with v2 
And are there any compatibility problems with the rollback?

Many thanks

**Comment by michaelinthecloud** [comment]
Customers can rollback the CloudFormation stack created using the v2.0.0 templates, by using the CloudFormation templates of v1.4.0 available [here](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/templates.html), they can use the same instructions for updating the template provided [here](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/deployment.html)

**Comment by bbenson29** [comment]
Can be close now.
