### ISSUE TITLE
Can we have multiple periods for a single day?

### ISSUE THREAD

**Issue by HimaBinduSariga** [aws-solutions/aws-instance-scheduler#303]
I need to schedule my instance in such a way that the instance should start/stop multiple times in a day.

For example:

Requirement is -
Mon-3am to 10am
Mon-3pm to 4pm

so I have created two periods 

period1:
Begin time= 3:00
End time= 10:00

period2:
Begin time= 15:00
End time= 16:00

I have created a schedule with two periods

schedule tag is getting created for the instances but schedule is not working as expected.

I would like to know setting multiple periods for one instance on the day will work? If yes! Please help me out in this.

**Comment by praveenis** [comment]
Hi @HimaBinduSariga,

scheduling instances multiple times a day is supported by the solution. 

Sample Schedule and Periods:

Schedule:

{
  "type": {
    "S": "schedule"
  },
  "name": {
    "S": "test-schedule"
  },
  "timezone": {
    "S": "US/Eastern"
  },
  "periods": {
    "SS": [
      "test-period1",
      "test-period2"
    ]
  }
}

Periods:

{
  "type": {
    "S": "period"
  },
  "name": {
    "S": "test-period1"
  },
  "begintime": {
    "S": "03:00"
  },
  "endtime": {
    "S": "10:00"
  },
  "weekdays": {
    "SS": [
      "mon-sun"
    ]
  }
}

{
  "type": {
    "S": "period"
  },
  "name": {
    "S": "test-period2"
  },
  "begintime": {
    "S": "15:00"
  },
  "endtime": {
    "S": "16:00"
  },
  "weekdays": {
    "SS": [
      "mon-sun"
    ]
  }
}

Can you please try out the above sample and if it didn't work can you please share the '<solutions-stack-name>-logs' CloudWatch logs for the start time.

Thanks,
Praveen
