### ISSUE TITLE
schedule failed to startup the rest instances when one instance failed to startup

### ISSUE THREAD

**Issue by daijing01** [aws-solutions/aws-instance-scheduler#304]
I created an instance scheduler and add to 8 instances, I noticed 8 instances don't startup during office hours. Further troubleshooting found one of the instances had EBS problem. Shouldn't scheduler skip that problem instance and startup the rest of instances?

**Comment by praveenis** [comment]
Hi @daijing01 

Currently the solution batches up the instances which are to be started and sends a batch request, so if one of the instance in the batch has an instance whose configuration is missing and is in a state where it cannot be started, all the instances in the batch will not be started. Also the batching is important it reduces the number of API calls required by the EC2 service and also improves the performance of the solution in a large scale. As a workaround there is an environment variable 'START_EC2_BATCH_SIZE' in the lambda function '<solution_stack_name>-InstanceSchedulerMain' which will reduce this batch size to 1 will skip the problematic instance and startup the rest of the instances. downside to this approach is which increases the API calls required by the EC2 services and it may also impact performance of the solution.

Thanks,
Praveen

**Comment by daijing01** [comment]
Praveen,
Thanks, we will set the environment to 1. 


Jing
