### ISSUE TITLE
Instance scheduler lambda concurrency count is too high

### ISSUE THREAD

**Issue by anuj1366** [aws-solutions/aws-instance-scheduler#307]
Hi Team
I am running Instance scheduler solution every hour for 600 account for single region for both services ec2 and rds.
Lambda timeout is set to 10 minutes and memory is set to 320 mb.
It means every hour count of lambda invocation will be = 600 *1 *2= 1200
I have run this solution for one month and that time lambda concurrency count was 70-80 and it takes around 4 minute to comlete the scheduling of ec2 and rds instances in all the 600 account.
In this case lambda average duration was under 10 sec

But now from last few days lambda concurrency count increased to 1000 and it takes around 1 minute to complete the scheduling of ec2 and rds instances in all the 600 account.
In this case lambda average duration increased to 200 seconds because of that solution cost has been increased.

Could you please let me know what could be the reason that has increased the lambda concurrency count without changing anything in solution.
Do let me know if you need more information.

**Comment by anuj1366** [comment]
I have noticed logger.flush() function is taking more time in this issue.
self._logger.flush() code is present inside finally block in handle_request() method which is present in file "scheduler_request_handler.py".
whole try block inside handle_request() method is taking maximum 2 second but flush function is taking around 30sec -60 sec. because of that Instance scheduler lambda average duration is high which increase the lambda cost as well.

**Comment by gockle** [comment]
Hi @anuj1366 

Based on the information provided there multiple options that can be explored,

1. Has anything changed in the account where the solution is hosted? example are there other Lambda functions being used in the same account? or Has there been any usage increase in the number of CloudWatch API calls being made in that account?
2. The `logger.flush()` is there to make sure what ever log statements are processed to the CloudWatch logs, you can if chose to comment it, and then if in the future you encounter any issue uncomment it to retrieve log events. Let us know if you face any additional issue when commenting the `logger.flush()` line in finally.

**Comment by anuj1366** [comment]
@gockle 
1. We have not changed anything in the account where the solution is hosted.
2. We have commented the code inside flush() function and after that solution is working perfectly fine without any issue.

I have analyze the issue in more details and figure out below line is causing the delay in solution which is present inside flush() method in logger.py file.

**resp = self.client.describe_log_streams_with_retries(logGroupName=self._loggroup, logStreamNamePrefix=self._logstream)**

Currently there are 3000 log stream inside a log group and validity of log is 1 months. 
I am not sure why suddenly above api call has started taking more time.

We don't want to comment the flush() function as its a production environment and we may require logs in future for debug the issue or any other analysis.

**Comment by gockle** [comment]
@anuj1366 

Thanks for the further details, we will review the describe API calls to cloudwatch.

**Comment by Liltonar** [comment]
@gockle 
We've encountered the same issue since March 14th and together with AWS CloudWatch Support we came to this:
> Yes, around the mentioned date and time, your DescribeLogStreams API calls were throttled due to 5 TPS limit. 
>  
> At time of this wring I can still see quite large number of DescribeLogStreams API calls (2460 in 15 mins interval) .  I have randomly found a timestamp , 2022-05-02T01:34:48.000Z when there were 8 DescribeLogStreams call logged in CloudTrail. 
> 
> Furthermore, API calls like DescribeLogStreams are designed for human interaction and not for automation, so you receive an error and the API call is throttled [1]. From internal document, I can see suggestion that to use PutLogEvents instead of DescribeLogStreams. 
> 
> To write logs to the specified log stream, you must include the sequence token in the request. This was last extracted from the response to the previous call. In some cases, you can use the DescribeLogStreams API to get the next sequence token for the log stream before calling PutLogEvent. The PutLogEvent API has a much higher limit than DescribeLogsStream, and this causes throttling. To mitigate this, use the PutLogEvents API to get the sequence instead of DescribeLogStreams. You receive a 400 status code when you use the PutLogEvents API without a sequence token, but with this error message you get the next sequence token. You can use this sequence token again with the PutLogEvents API.

We commented out "self._logger.flush()" in file "scheduler_request_handler.py", but still encounter much higher run times.
The average duration increased from ~4,500-5,500 ms before March 14th to ~50,000-60,000 ms after March 14th with disabled logger.flush.

**Comment by aijunpeng** [comment]
The issue has been addressed in v1.4.1

**Comment by anuj1366** [comment]
@gockle @aijunpeng 
Thank you for providing the fix.
