### ISSUE TITLE
PFR: scale EBS volume performance characteristics

### ISSUE THREAD

**Issue by elduds** [aws-solutions/aws-instance-scheduler#308]
I have a business requirement for our SAP systems to increase the throughput on HANA database disks for only a few days per month. Typically, the disks can survive on 500 MBps throughput, however during end of month the performance required is 1000 MBps. Currently, they are provisioned 24/7 at 1000 MBps which is wasteful.

Given throughput and IOPS can be scaled independently on gp3 volumes it seems like this feature would be a great improvement for the instance scheduler.

**Comment by gockle** [comment]
Hi @elduds I recommend to explore AWS Systems Manager to automate this action. The requirement can be to modify the resource in SSM Automation Document, the AWS Systems Manager State Manager console can be used to setup automation for this document and run on various period/frequency configuration using CRON expressions.
