### ISSUE TITLE
Schedule is unknown

### ISSUE THREAD

**Issue by createchange** [aws-solutions/aws-instance-scheduler#318]
Hello, I deployed this solution with a central account managing various other accounts. Yesterday in testing, I configured a schedule and a TEST period. Once I validated that the instance in question stopped and started, I replaced the period in the schedule with the correct period (I duplicated the test period and modified only the start/stop times).

The job now fails, with the following error:

`"WARNING : Skipping instance EC2:i-<id> (<instance_name>) in region us-east-1 for account <account_num>, schedule name \"amd-odbc-automation-schedule\" is unknown",`

I have attempted to create the schedule entry via both DynamoDB directly, as well as using the CLI tool. I have confirmed that the tag applied to the instance is correct with no whitespace, either leading or trailing. Upon checking for schedule usage via the CLI, this particular schedule is not found while another is...

```shell
~ ➜  scheduler-cli --version
scheduler-cli v1.4.0

# The schedule is question is shown in describe-schedules
~ ✗  scheduler-cli describe-schedules --stack instance-scheduler-for-ec2-and-rds --region us-east-1 --profile admin-admin | jq '.Schedules[] | select(.Name == "amd-odbc-automation-schedule") | .'
{
  "UseMaintenanceWindow": false,
  "StopNewInstances": false,
  "UseMetrics": false,
  "Hibernate": false,
  "Timezone": "US/Mountain",
  "Enforced": false,
  "RetainRunning": false,
  "Periods": [
    "amd-odbc-automation-period"
  ],
  "Name": "amd-odbc-automation-schedule",
  "Type": "schedule"
}

# But is not found when querying directly for it
~ ➜  scheduler-cli describe-schedule-usage --stack instance-scheduler-for-ec2-and-rds --region us-east-1 --profile admin-admin --name amd-odbc-automation-schedule
Not found: schedule amd-odbc-automation-schedule does not exist

# This schedule is found when using describe-schedules
~ ✗  scheduler-cli describe-schedules --stack instance-scheduler-for-ec2-and-rds --region us-east-1 --profile admin-admin | jq '.Schedules[] | select(.Name == "daily-eod-shutdown") | .'
{
  "UseMaintenanceWindow": false,
  "StopNewInstances": true,
  "UseMetrics": false,
  "Timezone": "US/Mountain",
  "Hibernate": false,
  "Enforced": false,
  "RetainRunning": false,
  "Periods": [
    "daily-eod-shutdown"
  ],
  "Name": "daily-eod-shutdown",
  "Type": "schedule"
}

# And also found when querying directly for it
~ ➜  scheduler-cli describe-schedule-usage --stack instance-scheduler-for-ec2-and-rds --region us-east-1 --profile admin-admin --name daily-eod-shutdown
{
   "Schedule": "daily-eod-shutdown",
   "Usage": {
      "2022-06-17": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      }
   }
}
```

I am at a loss for what is happening. I have entered and re-entered, deleted and re-created:
- schedule name
- entire schedule entry
- EC2 instance tag

Yet it continues to fail.

Here are some screenshots:
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/29058450/174337208-5f8eab1a-b08d-4b0d-8297-1d121496031c.png">

<img width="695" alt="image" src="https://user-images.githubusercontent.com/29058450/174337315-2b4aef2e-7bba-40bd-9856-b6fb39140ae6.png">

From the last screenshot, you can see that the `state` tag is set, which was done by the automation when it worked initially.

I'm at a loss. Guidance appreciated!

**Comment by createchange** [comment]
I (re-)re-created it via the `scheduler-cli` and it took this time. We can see my recreations were identical.

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/29058450/174394656-34f6b3fd-9fc3-4335-9370-241b13d8bdae.png">

Still lost, but happy that I won't break a scheduled task like I did this morning.

**Comment by createchange** [comment]
I lied - I changed one more thing... I removed the `endtime` on the single period to ensure that recreating the schedule didn't turn off an instance that was actively being used. This is what the period looks like:

```json
{
  "Begintime": "23:30",
  "Endtime": "02:00",
  "Description": "Time frame that AMD ODBC Server script runs",
  "Weekdays": [
    "wed",
    "sat",
    "tue",
    "thu",
    "mon",
    "sun",
    "fri"
  ],
  "Name": "amd-odbc-automation-period",
  "Type": "period"
}
```
When I remove the `endtime`, it works. When I add it, it gives me the `schedule unknown` error.

How can I structure this? Would it be something like this?

```json
~ ➜  scheduler-cli describe-periods 
...
{
  "Begintime": "23:30",
  "Description": "Time frame that AMD ODBC Server script runs",
  "Weekdays": [
    "wed",
    "sat",
    "thu",
    "tue",
    "sun",
    "mon",
    "fri"
  ],
  "Name": "amd-odbc-automation-start-period",
  "Type": "period"
}
{
  "Description": "Time frame that AMD ODBC Server script runs",
  "Endtime": "02:00",
  "Weekdays": [
    "wed",
    "sat",
    "thu",
    "tue",
    "sun",
    "mon",
    "fri"
  ],
  "Name": "amd-odbc-automation-stop-period",
  "Type": "period"
}
...
`

**Comment by deolank** [comment]
The End time cannot be earlier than the Start time for a period. A workaround for this is to use a timezone and make sure that End time is not earlier than start time on a given day.
