### ISSUE TITLE
AWS Organization support

### ISSUE THREAD

**Issue by basi123** [aws-solutions/aws-instance-scheduler#327]
Hi,

we are hitting CF limits when deploying the solution centrally and inputting the ARNs of roles for cross account access. We have 200+ accounts and expecting to have many more in some years.

It would be nice, if you could introduce AWS Organization support, e.g. like other (official) services on the list. https://docs.aws.amazon.com/organizations/latest/userguide/orgs_integrate_services_list.html

If that's not possible (b/c it's a solution, not a services), then some kind of workaround to achieve the same effect would be nice.

**Comment by elduds** [comment]
This is a great idea. My current workaround is a small python script in our account provisioning pipeline that grabs a list of account IDs and replaces the `cross_account_roles` attribute in the config item in DynamoDB. 

But having done this dynamically in code during invocation would be a good idea.

**Comment by elduds** [comment]
Also the ability to target an OU might be useful.

**Comment by exolain** [comment]
I had to update the Instance Scheduler code to support pulling the account list from the organization list.
It would be great if it were part of the original code. We manage around 700 accounts now.

**Comment by CrypticCabub** [comment]
> I had to update the Instance Scheduler code to support pulling the account list from the organization list. It would be great if it were part of the original code. We manage around 700 accounts now.

Glad to hear you were able to get something that works for you! 

Support for OUs is currently on our backlog and has been made a prioritized item for our next release

**Comment by exolain** [comment]
@CrypticCabub  that's great to know. What is the ETA for the next release? If we can remove our custom code that would be great to simply use the Instance Scheduler solution that would be ideal 👍

**Comment by CrypticCabub** [comment]
We don't have any ETAs that I can share for our next release at this time. However, our on-going development is now taking place in real-time on this repo, so you can follow along with current changes/progress and are welcome to contribute via PRs as well.

**Comment by CrypticCabub** [comment]
Organizational support has now released with [v1.5.0](https://github.com/aws-solutions/aws-instance-scheduler/releases/tag/v1.5.0)
