### ISSUE TITLE
AWS charging for Cloud Watch 0.5 Alarms

### ISSUE THREAD

**Issue by lunaSnowflake** [aws-solutions/aws-instance-scheduler#351]
I recently got a notification stating that I was charged $0.02 for a CLoud Watch Service. While the charges isn't bank breaking, I wanted to understand what are all the Cloud Watch bill components actually mean. 
I had a total of 30 alarms out of which I've deleted 6, remaining 24 Alarms out of which 6 are in the "In alarm" state (what does this "In alarm" means? -- I understood it to be those Alarms which could not be completely executed). 
All alarms are filled with Target tracking "Provisioned Capacity" and "Consumed Capacity". But all these alarms were created automatically when I made DynamoDB Tables. (All tables were created in same month)

If I am getting it right, I had 30 alarms out of which 10 should be free, which leaves me with extra 20 Alarms for which I should be charged. Then what is the component "Usage Quality" of "0.182" shows? -- and why it's in Decimal instead of a whole number?

After approaching AWS support, I came to know I'll get charged every time I make a new DynamoDB Table. Is that True?

![Screenshot (351)](https://user-images.githubusercontent.com/110465395/212485634-4eb64712-8fcc-472d-b8a0-d980604817d0.png)
![Screenshot (357)](https://user-images.githubusercontent.com/110465395/212485628-654993e4-8de7-4401-89f8-9808d883df63.png)

They Have been a really good help!

Update: Now in total I've charged for $0.05

![Screenshot (359)](https://user-images.githubusercontent.com/110465395/212487082-09a7fb02-6d41-4d31-841f-76709a4e0446.png)

**Comment by lunaSnowflake** [comment]
No, I did not.

**Comment by lunaSnowflake** [comment]
Thanks for lighting fast replies!
I've gone deep into this lately, and understand what is going on here. What I did not understand is when I created DynamoDB tables it created a total of 30 Alarms out of which 10 should be free and 20 should be chargeable, Am I correct?
If so why I am getting charged for 0.5 Alarms and not for 20? And why it is even is fractions like 0.5?

**Comment by CrypticCabub** [comment]
The billing is in "alarm months" so if you were to have 15 alarms for a full month you would get charged for 15 "alarm months" , but if you had those same 15 alarms for only half of the month you would get get billed for 7.5 "alarm months" (15 * .5)

**Comment by lunaSnowflake** [comment]
Ahh! I see that's what I was not enlightened about. Thanks that helped! I was not thinking straight probably too much confusion all over the internet.
**Last question**, how much time does it take for my "Alarm" bills to get reflected in my account? I am assuming it does not reflect at the beginning of each new month, because my alarms were created somewhere beginning of this month only (Jan 2023)?

**Comment by lunaSnowflake** [comment]
I got my answer somewhere between those lines.
Again you guys were a huge help, Thanks a lot!😀
