### ISSUE TITLE
python: 3.10 

### ISSUE THREAD

**Issue by kra5io** [aws-solutions/aws-instance-scheduler#366]
Hello,

How is this supposed to work with runtime 3.10 when there is no support in aws for 3.10 yet?

Cheers,
Krasi

**Comment by CrypticCabub** [comment]
Hi @kra5io 

We are currently using Python 3.10 as the executing environment for our build pipeline, but the lambda code itself runs on Python 3.9 as specified in the infrastructure code [here](https://github.com/aws-solutions/aws-instance-scheduler/blob/ee225801c07c286d8563eb1913e25f317e5bd8e0/source/lib/aws-instance-scheduler-stack.ts#L305)

**Comment by kra5io** [comment]
Hi,

Thanks for the reply. Closing this one.

Cheers,
Krasi
