### ISSUE TITLE
Instance Scheduler for aws organizations

### ISSUE THREAD

**Issue by natalia-1702** [aws-solutions/aws-instance-scheduler#389]
We are going to implement Instance Scheduler solution for very dynamic AWS Organisation, where we have more than 100 accounts and we deploy new accounts every week.

Instance Scheduler is suitable for static env  where we have X accounts and don't add new accounts or add them not really often.

In case of dynamic AWS  env- as I mentioned earlier we are adding new accounts all the time. So we are going to deploy MAIN CF stack into some central account. And Remote stacks will be deployed to all workload/spoke accounts. 

When we create new accounts in AWS we need to deploy to that account Remote Instance Scheduler stack ( we can automate it via stacksets) - BUT  somehow we need to pass ARN (it is always unique)  of the role ( which is created by Remote Instance Scheduler stack) to MainCF stack in Central account as parameter and update that Main stack.

We are considering such option: 
when new account is being created we invoke some lambda function ( automatically)  which finds ARN of that newly created role in the new account and passes it to AWS Codecommit and update main CF stack in Central account. 

It looks like a bit complicated customisation.

**Is there some other options for big organisations? some best practices?**  

Thank you.

**Comment by nalalia-1702** [comment]
hi @gockle , sounds good! 

What is approximate ETA? 

Thank you.

**Comment by natalia-1702** [comment]
hi @CrypticCabub sorry for tagging you here. probably you know approximate ETA for this feature? 

Thanks.

**Comment by CrypticCabub** [comment]
@natalia-1702 no worries, we are targeting Q2 for the release

**Comment by natalia-1702** [comment]
@CrypticCabub thank you.

**Comment by natalia-1702** [comment]
@CrypticCabub @gockle 
We were thinking about some workaround solution while this new feature isn't released. 

**We considering :**
-remote stack easy to deploy in new accounts via stack sets. 
-When NEW account is being created we invoke some lambda function ( automatically) which finds ARN of that newly created role(which deployed by remote stack) in the new account and pass it to AWS Codecommit(it will update parameter - list of ARNs) and **update main CF stack in Central account.**


Do you think we are on the right way? 

Thank you.

**Comment by natalia-1702** [comment]
Hi @gockle , thank you for the update.

currently we specify just naked list of RoleARNs in Parameter.json file:
    {
        "ParameterKey":"CrossAccountRoles",
	"ParameterValue":"ARN1,ARN2,ARN3,ARN4.......ARNn"
    },

If I correctly understand you to use parameter store we need to specify in the following format:
    {
        "ParameterKey":"CrossAccountRoles",
	"ParameterValue":"{param:**name_of_SSM_parameter**}"
    },


According to documentation we need to specify in different format:
    {
        "ParameterKey":"CrossAccountRoles",
	"ParameterValue":"{{resolve:ssm:name_of_SSM_parameter:10}}"
    },
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html



Which way is correct? Thank you.

**Comment by CrypticCabub** [comment]
Organizational support has now released with [v1.5.0](https://github.com/aws-solutions/aws-instance-scheduler/releases/tag/v1.5.0)
